### ISSUE TITLE
when i do   ./sbt  , i got error 

### ISSUE THREAD

**Issue by alagukaja** [d6y/liftmodules-imap-idle#2]
liftmodules-imap-idle-master$ ./sbt 
Getting org.scala-tools.sbt sbt_2.9.1 0.13.0 ...

:: problems summary ::
:::: WARNINGS
        module not found: org.scala-tools.sbt#sbt_2.9.1;0.13.0

```
==== local: tried

  /home/sirahu/.ivy2/local/org.scala-tools.sbt/sbt_2.9.1/0.13.0/ivys/ivy.xml

==== typesafe-ivy-releases: tried

  http://repo.typesafe.com/typesafe/ivy-releases/org.scala-tools.sbt/sbt_2.9.1/0.13.0/ivys/ivy.xml

==== Maven Central: tried

  http://repo1.maven.org/maven2/org/scala-tools/sbt/sbt_2.9.1/0.13.0/sbt_2.9.1-0.13.0.pom

==== Scala-Tools Maven2 Repository: tried

  http://scala-tools.org/repo-releases/org/scala-tools/sbt/sbt_2.9.1/0.13.0/sbt_2.9.1-0.13.0.pom

==== Scala-Tools Maven2 Snapshots Repository: tried

  http://scala-tools.org/repo-snapshots/org/scala-tools/sbt/sbt_2.9.1/0.13.0/sbt_2.9.1-0.13.0.pom

    ::::::::::::::::::::::::::::::::::::::::::::::

    ::          UNRESOLVED DEPENDENCIES         ::

    ::::::::::::::::::::::::::::::::::::::::::::::

    :: org.scala-tools.sbt#sbt_2.9.1;0.13.0: not found

    ::::::::::::::::::::::::::::::::::::::::::::::
```

:::: ERRORS
    Server access Error: Connection timed out url=http://scala-tools.org/repo-releases/org/scala-tools/sbt/sbt_2.9.1/0.13.0/sbt_2.9.1-0.13.0.pom

```
Server access Error: Connection timed out url=http://scala-tools.org/repo-snapshots/org/scala-tools/sbt/sbt_2.9.1/0.13.0/sbt_2.9.1-0.13.0.pom
```

:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
unresolved dependency: org.scala-tools.sbt#sbt_2.9.1;0.13.0: not found
Error during sbt execution: Error retrieving required libraries
  (see /home/sirahu/.sbt/boot/update.log for complete log)
Error: Could not retrieve sbt 0.13.0

please help me .. i can't able to run this module 
   or
give the sample IDLE IMAP connection  program 
such as following 

In this program , i give the user name and password directly .
how to create  IDLE connection in this program ?

My need  
1 Fetch the email from IMAP.  
2 If  new email coming , that mail also need to get .  
3 Don't connect the IMAP connection again "

Do u know about node.js ..? if u know then. Node.js have nodemailer for Email Receiver . it is IDLE connection , if new email appear it automatically fetch that . no need to connect again .

def connect = {
    val props = new Properties
    props.put("mail.store.protocal", "imaps")
    props.put("mail.imap.enableimapevents", "true")

```
val session = Session.getDefaultInstance(props)


val store =session.getStore("imaps")



store.connect("imap.gmail.com", "sm.muthu4@gmail.com", "sm.muthu44199")

val inbox = store.getFolder("kaja")
if(inbox.exists())
  inbox.open(Folder.READ_WRITE)
  else
    print("IMAP - folder INBOX not found. Carrying on in case it reappears")

    var message = inbox.getMessages()
    for(msg <- message)
    {
      print(msg.getSubject()+"\n")
    }
```

  }

**Comment by d6y** [comment]
Apologies: those SBT instructions were out of date.  Please pull the project and try again once you have SBT installed.

**Comment by alagukaja** [comment]
Hi Richard,

Do you know , how to get the email using Scala play framework ..

If you know,  please guide me

**Comment by alagukaja** [comment]
Again i got the error 

please find what is the error ..

sirahu@s1-mdu1-dt125:~/Downloads/liftmodules-imap-idle$ ./sbt 
[warn] The global sbt directory is now versioned and is located at /home/sirahu/.sbt/0.13.
[warn]   You are seeing this warning because there is global configuration in /home/sirahu/.sbt but not in /home/sirahu/.sbt/0.13.
[warn]   The global sbt directory may be changed via the sbt.global.base system property.
[info] Loading project definition from /home/sirahu/Downloads/liftmodules-imap-idle/project
/home/sirahu/Downloads/liftmodules-imap-idle/build.sbt:4: error: eof expected but ';' found.
 +liftVersion <<= liftVersion ?? "2.6-M2"
^
[error] Error parsing expression.  Ensure that settings are separated by blank lines.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by d6y** [comment]
Hello

Sorry, I don't know what the equivalent is for the Play Webframework. I suggest you ask on the mailing list (https://groups.google.com/forum/#!aboutgroup/play-framework) or stackoverflow - both are great sources of information for Play.

Regarding the error you have, I'm not sure what's causing that, but suspect it is something related to switching versions of SBT.  Can you please clone the project again in a fresh directory and see how that works for you.

**Comment by alagukaja** [comment]
Ok  
Thank you Richard

**Comment by d6y** [comment]
Closing this - please reopen if needed
